%global     commit     a205e671f590c0527568ff339a7a9d8724950223
%global     githash    %(c=%{commit}; echo ${c:0:7})
%global     gitdate    20140925

Name:     voglperf
Version:  0.2
Release:  4.%{gitdate}git%{githash}%{?dist}
Summary:  Benchmarking tool for Linux OpenGL games. Spews frame information, logs frametimes.

License:  MIT
URL:      https://github.com/ValveSoftware/voglperf
Source0:  https://github.com/ValveSoftware/voglperf/archive/%{commit}/%{name}-%{version}-%{gitdate}git%{githash}.tar.gz

# adjust libdir paths for the .so library
Patch1:   voglperf-p01-libdir.patch

# this project only seems to support x86_64 and i386
ExcludeArch:    armhfp

BuildRequires:  gcc-c++
BuildRequires:  cmake
BuildRequires:  ncurses-devel
BuildRequires:  mesa-libGL-devel

# RPM automatically discovers 'libGL.so()(64bit)' as a requirement, however in Fedora we only have
# mesa-libGL providing 'libGL' or 'libGL.so.1()(64bit)'. voglperf uses some fake libGL.so library
# to get this dependency into the list (see `src/libGL`). The only approach I found is to exclude
# the autogenerated dependency and replace it with a correct one.
# http://www.rpm.org/max-rpm/s1-rpm-depend-auto-depend.html
# https://fedoraproject.org/wiki/Packaging:AutoProvidesAndRequiresFiltering
%global __requires_exclude ^libGL\\.so.*
Requires:       mesa-libGL%{?_isa}

%description
Benchmarking tool for Linux OpenGL games. Spews frame information, logs frametimes. Makes it easy
to benchmark Steam games, but can be used to benchmark any OpenGL application (just provide its
full path as an argument).

%prep
%setup -q -n %{name}-%{commit}
%patch1 -p 1

%build
make %{?_smp_mflags}

%install
# there is no support for `make install`, so we need to emulate it manually
# copy the library
mkdir -p %{buildroot}/%{_libdir}/%{name}/
cp -p bin/libvoglperf*.so %{buildroot}/%{_libdir}/%{name}/
chmod 644 %{buildroot}/%{_libdir}/%{name}/libvoglperf*.so
# copy the executable
mkdir -p %{buildroot}/%{_bindir}/
cp -p bin/voglperfrun* %{buildroot}/%{_bindir}/

%files
%{_bindir}/*
%{_libdir}/%{name}/
%doc README.md
%doc screenshot.png
%license LICENSE

%changelog
* Wed Feb 24 2016 Kamil Páral <kparal@redhat.com> - 0.2-4.20140925gita205e67
- install library to /usr/lib*/voglperf

* Wed Feb 24 2016 Kamil Páral <kparal@redhat.com> - 0.2-3.20140925gita205e67
- clarify that non-steam games are also supported

* Tue Feb 23 2016 Kamil Páral <kparal@redhat.com> - 0.2-2.20140925gita205e67
- add BuildRequires:  gcc-c++

* Fri Feb 19 2016 Kamil Páral <kparal@redhat.com> - 0.2-1.20140925gita205e67
- initial release from 20140925 (git version)
